# Description
# ===========
# This playbook creates 
#	- a PostgreSQL server 
#	- an Instance 'postgres'
# 	- an additional Instance 'db03'
#	- a Firewall rule which allows access from define IP-range
# Parameters :
#	rg_name
#  	az_location
#	pg_srv_name
#	db_name
# How to execute
# 	ansible-playbook postgresql_deploy.yml -e rg_name=myrg -e az_location=westeurope
---
- hosts: localhost
  vars:
    myaction: present						# present: Deploy resources
    resource_group: "{{ rg_name |default('test-rg')}}"
    location: "{{ az_location |default('westeurope')}}"
    postgresqlserver_name: "{{ pg_srv_name |default('postgresql-03')}}" 
    postgresqldb_name: "{{ db_name |default('db03')}}"
    admin_username: postgres
    admin_password: Abcpasswordxyz12!
    postgresql_firewallrule_start_ip: 178.197.231.10
    postgresql_firewallrule_end_ip: 178.197.231.254
  roles:
    - azure_rg_deploy
    - postgresql_server_deploy
    - postgresql_database_deploy
    - postgresql_firewallrule_deploy
