# Description
# ===========
# This playbook deploys an RG
# Parameters :
#	rg_name
#	dest_location
# How to execute
# 	ansible-playbook postgresql_destroy.yml -e rg_name=myrg 

---
- hosts: localhost
  vars:
    myaction: present					# absent: destroy resources
    resource_group: "{{ rg_name |default('test-rg')}}"
    location: "{{ dest_location |default('eastus')}}"
  roles:
    - azure_rg_deploy
