# Description
# ===========
# This playbook destroys a PostgreSQL server and an instance of PostgreSQL Database
# Parameters :
#	rg_name
# How to execute
# 	ansible-playbook postgresql_destroy.yml -e rg_name=myrg 

---
- hosts: localhost
  vars:
    myaction: absent					# absent: destroy resources
    resource_group: "{{ rg_name |default('test-rg')}}"
  roles:
    - azure_rg_destroy
