# Description
# ===========
# This playbook deploys a Subnet within a Vnet
# Parameters :
#	rg_name
#       vnet_name
#	address_prefixes
#	subnet_name
# How to execute
# 	ansible-playbook <playbook-file> -e rg_name=myrg -e vnet-name=vnet1 ..
---
- hosts: localhost
  vars:
    resource_group: "{{ rg_name |default('test-rg')}}"
    vnetwork_name: "{{ vnet_name |default('spoke100-vnet')}}"
    address_prefixes_cidr: "{{ address_prefixes |default('10.1.0.0/24')}}"
    name: "{{ subnet_name |default('subnet')}}"
  roles:
    - azure_subnet_deploy
