---
- name: List RG components
  azure_rm_resourcegroup_facts:
    name: "{{ resource_group }}"
    list_resources: yes
  register: rg_result
# - debug: var=rg_result verbosity=1
- name: Resource group
  azure_rm_resourcegroup:
    name: "{{ resource_group }}"
    state: "{{ myaction }}"
    force_delete_nonempty: false		# true would remove RG even though resources exist in it!
