---
- name: Firewall rule for remote accessing PostgreSQL    
  azure_rm_postgresqlfirewallrule:
    resource_group: "{{ resource_group }}"
    server_name: "{{ postgresqlserver_name }}"
    name: rule1
    state: "{{ myaction }}"
